---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.


## Step 12.1 — Prerequisites
- Phillip's note: No problems setting up the Prerequisites
- betsy's note: no problems 

## Step 12.2 — Make a repo on GitHub
- Phillip's note: No problems connecting github to classroom/creating repo
- betsy's note:remember that you have to go to the terminal


## Step 12.3 — Clone the test GitHub repository to your computer via RStudio
- Phillip's note: No issues cloning the repo!
- betsy's note: make sure you know where the new project is being saved


## Step 12.4 — Make local changes, save, commit
- Phillip's note: added line to readme, then staged/commit from RStudio!
- betsy's note: remember to save before committing

## Step 12.5 — Push your local changes online to GitHub
- Phillip's note: Pushed through RStudio, no issue.
- betsy's note: push 

## Step 12.6 — Confirm the local change propagated to the GitHub remote
- Phillip's note: No problems! Commit can be found in repo's history
- betsy's note: reload github

## Step 12.7 — Clean up
- Phillip's note: Not deleting repo as instructed. 
- betsy's note: no deleting for this lab

